version: '3.9'
services:
    cache:
        image: redis
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    db:
        image: postgis/postgis
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: trentino-trasporti
        ports:
            - '5432:5432'
        expose:
            - '5432'
        
    node-app:
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on:
            - db
            - cache
        volumes:
            - ./src:/app/src
        env_file:
            - env.dev
        ports:
            - '8080:8080'
        expose:
            - '8080'
        command: npm run dev:migrate
