version: '3.9'
services:
  app:
    container_name: trentino-trasporti-graphql-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env.prod
    ports:
      - '8080:8080'
    