import { NonEmptyArray } from 'type-graphql'

import {
    AgencyRelationsResolver,
    AggregateAgencyResolver,
    AggregateCalendarDateResolver,
    AggregateCalendarResolver,
    AggregateRouteResolver,
    AggregateShapeResolver,
    AggregateShapeSequenceResolver,
    AggregateStopResolver,
    AggregateStopTimeResolver,
    AggregateTransferResolver,
    AggregateTripResolver,
    CalendarDateRelationsResolver,
    CalendarRelationsResolver,
    FindFirstAgencyResolver,
    FindFirstCalendarDateResolver,
    FindFirstCalendarResolver,
    FindFirstRouteResolver,
    FindFirstShapeResolver,
    FindFirstShapeSequenceResolver,
    FindFirstStopResolver,
    FindFirstStopTimeResolver,
    FindFirstTransferResolver,
    FindFirstTripResolver,
    FindManyAgencyResolver,
    FindManyCalendarDateResolver,
    FindManyCalendarResolver,
    FindManyRouteResolver,
    FindManyShapeResolver,
    FindManyShapeSequenceResolver,
    FindManyStopResolver,
    FindManyStopTimeResolver,
    FindManyTransferResolver,
    FindManyTripResolver,
    FindUniqueAgencyResolver,
    FindUniqueCalendarDateResolver,
    FindUniqueCalendarResolver,
    FindUniqueRouteResolver,
    FindUniqueShapeResolver,
    FindUniqueShapeSequenceResolver,
    FindUniqueStopResolver,
    FindUniqueStopTimeResolver,
    FindUniqueTransferResolver,
    FindUniqueTripResolver,
    GroupByAgencyResolver,
    GroupByCalendarDateResolver,
    GroupByCalendarResolver,
    GroupByRouteResolver,
    GroupByShapeResolver,
    GroupByShapeSequenceResolver,
    GroupByStopResolver,
    GroupByStopTimeResolver,
    GroupByTransferResolver,
    GroupByTripResolver,
    RouteRelationsResolver,
    ShapeRelationsResolver,
    ShapeSequenceRelationsResolver,
    StopRelationsResolver,
    StopTimeRelationsResolver,
    TransferRelationsResolver,
    TripRelationsResolver
} from '../generated'

import {
    CustomStopResolver,
    CustomStopTimeResolver,
    CustomTripResolver
} from './customResolvers'

const resolvers: NonEmptyArray<Function> | NonEmptyArray<string> = [
    // Agency
    AggregateAgencyResolver,
    FindFirstAgencyResolver,
    FindManyAgencyResolver,
    FindUniqueAgencyResolver,
    GroupByAgencyResolver,
    // Calendar
    AggregateCalendarResolver,
    FindFirstCalendarResolver,
    FindManyCalendarResolver,
    FindUniqueCalendarResolver,
    GroupByCalendarResolver,
    // CalendarDate
    AggregateCalendarDateResolver,
    FindFirstCalendarDateResolver,
    FindManyCalendarDateResolver,
    FindUniqueCalendarDateResolver,
    GroupByCalendarDateResolver,
    // Route
    AggregateRouteResolver,
    FindFirstRouteResolver,
    FindManyRouteResolver,
    FindUniqueRouteResolver,
    GroupByRouteResolver,
    // Shape
    AggregateShapeResolver,
    FindFirstShapeResolver,
    FindManyShapeResolver,
    FindUniqueShapeResolver,
    GroupByShapeResolver,
    // ShapeSequence
    AggregateShapeSequenceResolver,
    FindFirstShapeSequenceResolver,
    FindManyShapeSequenceResolver,
    FindUniqueShapeSequenceResolver,
    GroupByShapeSequenceResolver,
    // Stop
    AggregateStopResolver,
    FindFirstStopResolver,
    FindManyStopResolver,
    FindUniqueStopResolver,
    GroupByStopResolver,
    // StopTime
    AggregateStopTimeResolver,
    FindFirstStopTimeResolver,
    FindManyStopTimeResolver,
    FindUniqueStopTimeResolver,
    GroupByStopTimeResolver,
    // Transfer
    AggregateTransferResolver,
    FindFirstTransferResolver,
    FindManyTransferResolver,
    FindUniqueTransferResolver,
    GroupByTransferResolver,
    // Trip
    AggregateTripResolver,
    FindFirstTripResolver,
    FindManyTripResolver,
    FindUniqueTripResolver,
    GroupByTripResolver,
    // Relations
    AgencyRelationsResolver,
    CalendarRelationsResolver,
    CalendarDateRelationsResolver,
    RouteRelationsResolver,
    ShapeRelationsResolver,
    ShapeSequenceRelationsResolver,
    StopRelationsResolver,
    StopTimeRelationsResolver,
    TransferRelationsResolver,
    TripRelationsResolver,
    // Custom
    CustomStopResolver,
    CustomStopTimeResolver,
    CustomTripResolver
]

export default resolvers
